name = "wilderness"
author = "Vercte"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "349545df4115176ece8161e9ea00a29590a37ef7c06046aa834c5a564ea97541"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
